version: "3.9"

services:
  api:
    build: .
    container_name: brain-agriculture-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/brainagriculture
      - NODE_ENV=development
    env_file:
      - .env.docker

  db:
    image: postgres:14
    container_name: brain-agriculture-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainagriculture
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
